import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { build } from "esbuild";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const extensionDir = path.resolve(scriptDir, "..");
const rootDir = path.resolve(extensionDir, "..");
const source = path.join(extensionDir, "src", "content-entry.js");
const manifestPath = path.join(extensionDir, "manifest.json");
const isDev = process.argv.includes("--dev");
const output = isDev
  ? path.join(rootDir, "dist", ".build", "content-dev.js")
  : path.join(extensionDir, "content.js");

await mkdir(path.dirname(output), { recursive: true });
await build({
  entryPoints: [source],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: ["chrome120"],
  outfile: output,
  sourcemap: false,
  minify: !isDev,
  legalComments: "none",
  define: {
    __PSETTER_DEV_BUILD__: JSON.stringify(isDev),
  },
  banner: {
    js: "// Generated by psetter-extension/scripts/build.mjs. Edit src/, not this file.",
  },
});

const generatedBanner =
  "// Generated by psetter-extension/scripts/build.mjs. Edit src/, not this file.\n";
const generatedSource = await readFile(output, "utf8");
if (!generatedSource.startsWith(generatedBanner)) {
  throw new Error("Generated content bundle is missing its expected banner.");
}
const generatedBody = generatedSource
  .slice(generatedBanner.length)
  .replace(/^"use strict";/, "");
await writeFile(output, `${generatedBanner}"use strict";${generatedBody}`, "utf8");

const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
const sourceVersion = JSON.parse(
  await readFile(path.join(extensionDir, "package.json"), "utf8"),
).version;
if (manifest.version !== sourceVersion) {
  throw new Error(`Version mismatch: manifest ${manifest.version}, package ${sourceVersion}`);
}

console.log(`Built ${path.relative(extensionDir, output)}`);

export { output as builtContentPath };
