import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { build } from "esbuild";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const extensionDir = path.resolve(scriptDir, "..");
const rootDir = path.resolve(extensionDir, "..");
const source = path.join(extensionDir, "src", "content-entry.js");
const manifestPath = path.join(extensionDir, "manifest.json");
const isDev = process.argv.includes("--dev");

function runtimeConfigPlugin(runtimeConfigPath) {
  if (!runtimeConfigPath) return null;
  const publicRuntimeConfigPath = path.join(extensionDir, "runtime-config.js");
  const resolvedRuntimeConfigPath = path.resolve(runtimeConfigPath);
  return {
    name: "psetter-runtime-config-override",
    setup(buildContext) {
      buildContext.onResolve({ filter: /runtime-config\.js$/ }, (args) => {
        const resolved = path.resolve(args.resolveDir, args.path);
        return resolved === publicRuntimeConfigPath
          ? { path: resolvedRuntimeConfigPath }
          : undefined;
      });
    },
  };
}

async function buildContent({ runtimeConfigPath = null, outputPath = null } = {}) {
  const output =
    outputPath ??
    (isDev
      ? path.join(rootDir, "dist", ".build", "content-dev.js")
      : path.join(extensionDir, "content.js"));
  const plugin = runtimeConfigPlugin(runtimeConfigPath);

  await mkdir(path.dirname(output), { recursive: true });
  await build({
    entryPoints: [source],
    bundle: true,
    format: "iife",
    platform: "browser",
    target: ["chrome120"],
    outfile: output,
    sourcemap: false,
    minify: !isDev,
    legalComments: "none",
    define: {
      __PSETTER_DEV_BUILD__: JSON.stringify(isDev),
    },
    plugins: plugin ? [plugin] : [],
    banner: {
      js: "// Generated by psetter-extension/scripts/build.mjs. Edit src/, not this file.",
    },
  });

  const generatedBanner =
    "// Generated by psetter-extension/scripts/build.mjs. Edit src/, not this file.\n";
  const generatedSource = await readFile(output, "utf8");
  if (!generatedSource.startsWith(generatedBanner)) {
    throw new Error("Generated content bundle is missing its expected banner.");
  }
  const generatedBody = generatedSource
    .slice(generatedBanner.length)
    .replace(/^"use strict";/, "");
  await writeFile(output, `${generatedBanner}"use strict";${generatedBody}`, "utf8");

  const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
  const sourceVersion = JSON.parse(
    await readFile(path.join(extensionDir, "package.json"), "utf8"),
  ).version;
  if (manifest.version !== sourceVersion) {
    throw new Error(`Version mismatch: manifest ${manifest.version}, package ${sourceVersion}`);
  }

  console.log(`Built ${path.relative(extensionDir, output)}`);
  return output;
}

const invokedDirectly =
  process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
const builtContentPath = invokedDirectly ? await buildContent() : null;

export { buildContent, builtContentPath };
